### PR TITLE
Add optional version command to launcher

### PR DESCRIPTION
**Pull request by marcelldls**
`version` is a useful cli command - this option adds the command if the developer passes a version that should be output when executing `${my_fastcs_device} version`

### CODE REVIEW

**Comment by GDYendell** [comment]
Would it be possible to print the FastCS version as well as the controller version?

**Comment by marcelldls** [comment]
Thats a good idea

**Comment by marcelldls** [comment]
The default is that it will print FastCS version. If a version of the implemented controller is passed, it will also be shown
```
(.venv) [esq51579@pc0146 FastCS]$ thorlabs-mff-fastcs version
INFO: PVXS QSRV2 is loaded, permitted, and ENABLED.
ThorlabsMFF: my_version
FastCS: 0.7.1.dev19+gdc6f1a0
```

**Review by GDYendell — APPROVED** [review]
Looks good.

Note if we move towards having a single FastCS application entry point then it will need to import the controller and could potentially get the controller version itself.

**Pull request merged**
